### ISSUE TITLE
Refine time slot response

### ISSUE THREAD

**Issue by Raphx** [Raphx/vmlauncher-server#4]
Time slot API response should be processed and returned in a better structure, rather that just `start` and `end` fields.

The suggested structure is as follows:

```json
{
  "id": 1,
  "machine": "machine name or hyperlinked url",
  "slots": [
    { "time": 9, "user": "user1" },
    { "time": 10, "user": "user2" }
  ]
}
```

**Comment by MachHach** [comment]
Mainly requires changes to:
- machines/models/Slot
- machines/serializers/SlotSerializer
- machines/views/SlotDetail
- machines/views/SlotList

Also affects (but not required yet):
- machines/validators/ValidStartEnd
- machines/tests/AuthenticatedAPITest (make_slot)
- machines/tests/AbstractSlotTest
- machines/tests/MachineToSlotRelationTest (add_slot_to_machine)
- machines/tests/SlotTest
- machines/tests/SlotFilterTest

**Comment by MachHach** [comment]
Discussed with issue reporter:
- Redefine a slot as a 1-hour time box for a specific machine (clients will only query for slots that are specific to the local date required).
- The [client implementation](https://github.com/Raphx/vmlauncher-2.0) should display a 24-slot timetable (this is raised as an [issue](https://github.com/Raphx/vmlauncher-2.0/issues/1) there).
- The JSON object should also contain _date_ attribute in addition to the above suggested structure.

**Comment by Raphx** [comment]
Nice.

These are some tasks to work on:

- [ ] Update the `slot` model with new structure, consisting of `date`, but without `start` and `end`
- [ ] Override `POST` request behaviour for `slot`. We are now accepting an array of slots from client
- [ ] Update implementation of validator for `slot`, since validation is now pure existence check, rather than date time ranges overlap
- [ ] Remove implementation on `GET` request params, which are `start` and `end`
- [ ] Add implementation on `GET` request params for `date`
- [ ] Add implementation on `GET` request params for `timezone`
- [ ] With both `date` and `timezone` request params, perform filtering on slots object
- [ ] Add tests 😄 

Are there anything else missing from this list?

**Comment by MachHach** [comment]
The concept of time slot per hour does not fit well with time zones with unusual offsets, e.g. Asia/Kathmandu with offset of 5:45.
Time slots booked by users of these time zones are not easily represented to users of time zones with zero-minute offsets.

Need further discussion on this (logic) issue.

**Comment by MachHach** [comment]
Time slot implementation once again should be changed:
- Server should store machine bookings (the Slot objects) as time spectrum, i.e. basically retaining the original implementation.
- GET requests to the server will return these time spectrum as individual 1-hour time slots to the client. Any resultant slots that are partially occupied (due to non-zero-minute timezone offsets such as _05:45_) will be returned as wholly-occupied slots.
- GET requests will need query strings `timezone` and `dateoffset`, for the server to determine what data to return for the required local date in the specified timezone (this also affects whether there is "partial slots" due to non-zero-minute timezone offsets).
- POST requests to the server will contain the local timezone, and a list of local date-times, where each of these date-times is a time slot to be booked by the client. These date-times will be combined and converted into time spectrum to be stored in the server.
- PATCH and DELETE requests should work similarly as well.

**Comment by Raphx** [comment]
Closing this issue since there was a design change as discussed.

Slot creation as time spectrum is done, the other halves being slot retrieval as time slots. This will be done in the upcoming implementation of `/api/timetable` API endpoint.

Issue will be closed soon with the merge of time slot creation implementation.
